---
name: Dismiss stale approvals

# yamllint disable-line rule:truthy
on:
  pull_request_target:
    branches:
      - devel
      - "release-v*"
    types:
      - synchronize

permissions:
  contents: read
  pull-requests: write

jobs:
  dismiss-stale-approvals:
    # Mergify used to preserve approvals in cases where it did
    # a force push. This job emualtes the same but for our bot.
    if: >
      github.repository == 'ceph/ceph-csi' &&
      github.actor != 'ceph-csi-bot' &&
      github.actor != 'mergify[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Dismiss approvals of the previous revision
        # yamllint disable-line rule:line-length
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3  # v9.0.0
        with:
          github-token: ${{ secrets.CEPH_CSI_BOT_TOKEN }}
          script: |
            const number = context.payload.pull_request.number
            const reviews = await github.paginate(
              github.rest.pulls.listReviews,
              {
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: number
              }
            )

            // Only dismiss approved reviews, preserve requested changes.
            for (const review of reviews) {
              if (review.state !== 'APPROVED') {
                continue
              }

              await github.rest.pulls.dismissReview({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: number,
                review_id: review.id,
                message: 'The pull request was updated, please review again.'
              })
            }
